version: "3.1"

services:
  #app:
    #container_name: "test_client"
    #image: node:latest
    #repository: 
    #ports:
      #- "3000:3000"

  #api:
    #container_name: "test_server"
    #image: node:latest
    #ports:
      #- "4321:4321"

  db:
    container_name: "test_db"
    image: postgres
    environment:
      POSTGRES_DB: psql
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
