version: "3.1"

services:
  #app:
    #container_name: "test_client"
    #image: node:latest
    #repository: 
    #ports:
      #- "5173:5173"

  #api:
    #container_name: "test_server"
    #image: node:18
    #build:
      #context: ./api/
      #dockerfile: ./api/Dockerfile
    #volumes:
      #- ./api:/server
    ##networks:
      ##- backend
    #working_dir: /server
    #ports:
      #- "8080:8080"
    #command: "npm run dev"

  db:
    container_name: "test_db"
    image: postgres
    environment:
      POSTGRES_DB: business_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    #networks:
      #- backend
    ports:
      - "5432:5432"
    volumes:
      - ./db:/data
    working_dir: /data

#networks:
  #backend:
    #driver: bridge

volumes:
  #api:
    #driver: local
  db:
    #driver: local
    name: "db"
