version: "3.1"

services:
  #app:
    #container_name: "test_client"
    #image: node:latest
    #repository: 
    #ports:
      #- "5173:5173"

  #api:
    #container_name: "test_server"
    #image: node:18
    #build:
      #context: ./api/
      ##dockerfile: ./api/Dockerfile
    #volumes:
      #- ./api:/server
    ##networks:
      ##- backend
    #working_dir: /server
    #ports:
      #- "8080:8080"
    #command: "npm run dev"

  db:
    container_name: "test_db"
    image: postgres
    environment:
      POSTGRES_DB: business_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    #networks:
      #- backend
    ports:
      - "5432:5432"
    volumes:
      - ./db:/data
    working_dir: /data
    #command:
      #- docker cp ./db/business.csv /data
    #command:
      #- postgres -c "CREATE DATABASE my_db;"
      #- postgres -c "CREATE TABLE IF NOT EXISTS business (name VARCHAR(80), state VARCHAR (2), city VARCHAR (50)); COPY business (name, state, city) FROM '/data/business.csv' DELIMITER ',' CSV;"


#networks:
  #backend:
    #driver: bridge

volumes:
  #api:
    #driver: local
  db:
    #driver: local
    name: "db"
