version: "3.1"

services:
  #app:
    #container_name: "test_client"
    #image: node:latest
    #repository: 
    #ports:
      #- "5173:5173"

  #api:
    #container_name: "test_server"
    #image: node:latest
    #ports:
      #- "8080:8080"

  db:
    container_name: "test_db"
    image: postgres
    environment:
      POSTGRES_DB: business_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - db:/data
    working_dir: /data

volumes:
  db:
    driver: local
